version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build: .
    volumes:
      - ./app:/var/www/html