version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
     # - ./app:/var/www/html
       - ./docker/nginx-main.conf:/etc/nginx/nginx.conf
       - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
       - ./docker/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf